concurrency:
  cancel-in-progress: true
  group: ${{ github.event.number }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Run hostname
      run: hostname
    - continue-on-error: true
      name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - continue-on-error: true
      name: Show hosts
      run: cat /etc/hosts
    - continue-on-error: true
      name: Checkout master
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11.0.16+8
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - continue-on-error: true
      env:
        PRODUCT_APIM_TEST_GROUPS: ${{ matrix.segment }}
      name: Build product-apim with Test.
      run: mvn clean install --file pom.xml -DskipBenchMarkTest=true -DskipRestartTests=true
    - continue-on-error: true
      if: always()
      name: Prepare upload testng report
      run: mv modules/integration/tests-integration/tests-backend/target/surefire-reports/TEST-TestSuite.xml
        TEST-TestSuite_${{ matrix.id }}.xml
    - continue-on-error: true
      if: always()
      name: Archive testng report
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: TEST-TestSuite_${{ matrix.id }}
        path: 'TEST-TestSuite_${{ matrix.id }}.xml

          '
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: integration_tests
    strategy:
      fail-fast: false
      matrix:
        include:
        - id: 1
          segment: group1
        - id: 2
          segment: group2
        - id: 3
          segment: group3
        - id: 4
          segment: group4
  run-benchmark-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Run hostname
      run: hostname
    - continue-on-error: true
      name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - continue-on-error: true
      name: Show hosts
      run: cat /etc/hosts
    - continue-on-error: true
      name: Checkout master
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11.0.16+8
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 10.x
    - continue-on-error: true
      name: Build product-apim with Test.
      run: mvn clean install --file pom.xml -DskipIntegrationTests=true
  show-report:
    if: ${{ always() && !cancelled() }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/download-artifact@v2
      with:
        path: reports
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: malinthaprasan/action-surefire-report@v1
      with:
        report_paths: reports/**/TEST-*.xml
name: APIM builder
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
